### ISSUE TITLE
Select block does not work as expected

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-form-builder#48]
1) as admin
2) create a new page with a select form block
3) add three options separated by a newline
4) save the form
-> the select widget will show a single option with all three options in one line instead of three separate options

![Edit-Page](https://user-images.githubusercontent.com/632105/103181153-310e8580-489e-11eb-8183-5ae08d0b46c9.png)

**Comment by iFlameing** [comment]
@tisto we are currently taking comma-separated choices otherwise it will be considered as one.

**Comment by tisto** [comment]
@iFlameing when we show a multi-line field the user expects one line per value. Can you please change the behavior and add a description to that field ("enter one value per line").
